class ApplicationController < ActionController::API
  include Response
  include Error

  def standardize(checks_params)
    if checks_params[:street]
      checks_params[:street].upcase!
      checks_params[:street].gsub!('ROAD','RD')
      checks_params[:street].gsub!('STREET','ST')
      checks_params[:street].gsub!('AVENUE','AVE')
      checks_params[:street].gsub!('NORTH','N')
      checks_params[:street].gsub!('SOUTH','S')
      checks_params[:street].gsub!('WEST','W')
      checks_params[:street].gsub!('EAST','E')
      checks_params[:street].gsub!('NORTHWEST','NW')
      checks_params[:street].gsub!('NORTHEAST','NE')
      checks_params[:street].gsub!('SOUTHEAST','SE')
      checks_params[:street].gsub!('SOUTHWEST','SW')
    end
    if checks_params[:city]
      checks_params[:city].upcase!
      checks_params[:city].gsub!('NORTH','N')
      checks_params[:city].gsub!('SOUTH','S')
      checks_params[:city].gsub!('WEST','W')
      checks_params[:city].gsub!('EAST','E')
      checks_params[:city].gsub!('NORTHWEST','NW')
      checks_params[:city].gsub!('NORTHEAST','NE')
      checks_params[:city].gsub!('SOUTHEAST','SE')
      checks_params[:city].gsub!('SOUTHWEST','SW')
    end
    if checks_params[:state]
      checks_params[:state].upcase!
      checks_params[:state].gsub!('ALABAMA','AL')
      checks_params[:state].gsub!('ALASKA','AK')
      checks_params[:state].gsub!('ARIZONA','AZ')
      checks_params[:state].gsub!('ARKANSAS','AR')
      checks_params[:state].gsub!('CALIFORNIA','CA')
      checks_params[:state].gsub!('COLORADO','CO')
      checks_params[:state].gsub!('CONNECTICUT','CT')
      checks_params[:state].gsub!('CONNECTICUT','CT')
      checks_params[:state].gsub!('DELEWARE','DE')
      checks_params[:state].gsub!('FLORIDA','FL')
      checks_params[:state].gsub!('GEORGIA','GA')
      checks_params[:state].gsub!('HAWAII','HI')
      checks_params[:state].gsub!('IDAHO','ID')
      checks_params[:state].gsub!('ILLINOIS','IL')
      checks_params[:state].gsub!('INDIANA','IN')
      checks_params[:state].gsub!('IOWA','IA')
      checks_params[:state].gsub!('KANSAS','KS')
      checks_params[:state].gsub!('KENTUCKY','KY')
      checks_params[:state].gsub!('LOUISIANA','LA')
      checks_params[:state].gsub!('MAINE','ME')
      checks_params[:state].gsub!('MASSACHUSETTS','MA')
      checks_params[:state].gsub!('MICHIGAN','MI')
      checks_params[:state].gsub!('MINNESOTA','MN')
      checks_params[:state].gsub!('MISSISSIPPI','MS')
      checks_params[:state].gsub!('MISSOURI','MO')
      checks_params[:state].gsub!('MONTANA','MT')
      checks_params[:state].gsub!('NEBRASKA','NE')
      checks_params[:state].gsub!('NEVADA','NV')
      checks_params[:state].gsub!('NEW HAMPSHIRE','NH')
      checks_params[:state].gsub!('NEW JERSEY','NJ')
      checks_params[:state].gsub!('NEW MEXICO','NM')
      checks_params[:state].gsub!('NEW YORK','NY')
      checks_params[:state].gsub!('NORTH CAROLINA','NC')
      checks_params[:state].gsub!('NORTH DAKOTA','ND')
      checks_params[:state].gsub!('OHIO','OH')
      checks_params[:state].gsub!('OKLAHOMA','OK')
      checks_params[:state].gsub!('OREGON','OR')
      checks_params[:state].gsub!('PENNSYLVANIA','PA')
      checks_params[:state].gsub!('RHODE ISLAND','RI')
      checks_params[:state].gsub!('SOUTH CAROLINA','SC')
      checks_params[:state].gsub!('SOUTH DAKOTA','SW')
      checks_params[:state].gsub!('TENNESSEE','TN')
      checks_params[:state].gsub!('TEXAS','TX')
      checks_params[:state].gsub!('UTAH','UT')
      checks_params[:state].gsub!('VERMONT','VT')
      checks_params[:state].gsub!('VIRGINIA','VA')
      checks_params[:state].gsub!('WASHINGTON','WA')
      checks_params[:state].gsub!('WEST VIRGINIA','WV')
      checks_params[:state].gsub!('WISCONSIN','WI')
      checks_params[:state].gsub!('WYOMING','WY')
      checks_params[:state].gsub!('AMERICAN AMOA','AS')
      checks_params[:state].gsub!('DISTRICT OF COLUMBIA','DC')
      checks_params[:state].gsub!('FEDERATED STATES OF MICRONESIA','FM')
      checks_params[:state].gsub!('GUAM','GU')
      checks_params[:state].gsub!('MARSHALL ISLANDS','MH')
      checks_params[:state].gsub!('NORTHERN MARINA ISLANDS','MP')
      checks_params[:state].gsub!('PALAU','PW')
      checks_params[:state].gsub!('PUERTO RICO','PR')
      checks_params[:state].gsub!('VIRGIN ISLANDS','VI')
    end
    return checks_params
  end
end
